export const routes = {
    LOGIN: 'LoginScreen',
    REGISTER: 'RegisterScreen',
    HOMEDRAWER : 'HomeDrawerScreen',
    HOME : 'HomeScreen',
    ACCOUNT : 'AccountScreen',
    CATEGORY : 'CategoryScreen',
    FAVOURITES : 'FavoritesScreen',
    PROFILE : 'ProfileScreen',
    ACCOUNTTAB : 'AccountTabScreen',
    NOTIFICATION : 'NotificationScreen',
    NOTIFICATIONDETAILS :'NotificationDetailsScreen',
    HOMEDETAIL : 'HomeDetailsScreen',
    HOMETAB : 'HomeTabScreen',
  };
